<?php

namespace App\Services;

use Spatie\Browsershot\Browsershot;

class PdfService
{
    /**
     * Generate PDF from view with proper header and footer
     *
     * @param string $view The view to render
     * @param array $data The data to pass to the view
     * @param string $orientation 'portrait' or 'landscape'
     * @return string Generated PDF content
     */
    public function generatePdf($view, $data, $orientation = 'portrait')
    {
        // Prepare data for the view
        $data['orientation'] = $orientation;
        $data['preparedBy'] = $data['preparedBy'] ?? auth()->user()->name ?? 'WAVE IO System';
        $data['title'] = $data['title'] ?? 'Report';
        $data['isRtl'] = $data['isRtl'] ?? false;

        // Add logo data
        $data['ssPlusLogoSrc'] = $this->prepareLogoData();

        // Render the HTML
        $html = view($view, $data)->render();

        // Generate PDF with Browsershot
        return Browsershot::html($html)
            ->setChromePath(env('PUPPETEER_EXECUTABLE_PATH'))
            ->format('A4')
            ->landscape($orientation === 'landscape')
            ->showBackground()
            ->margins(15, 15, 15, 15) // Top, right, bottom, left
            ->setOption('displayHeaderFooter', true)
            ->setOption('headerTemplate', ' ') // Empty header (handled in the view)
            ->setOption('footerTemplate', $this->getFooterTemplate())
            ->pdf();
    }

    /**
     * Prepare logo data
     * 
     * @return string Base64 encoded logo image
     */
    private function prepareLogoData()
    {
        $ssPlusLogoPath = resource_path('images/ssplus/logo-horizontal.png');
        if (file_exists($ssPlusLogoPath)) {
            $ssPlusLogoData = base64_encode(file_get_contents($ssPlusLogoPath));
            return 'data:image/png;base64,' . $ssPlusLogoData;
        }
        return '';
    }


    /**
     * Get footer HTML template for Browsershot
     * 
     * @return string Footer HTML template
     */
    private function getFooterTemplate()
    {
        return '
        <style>
        .footer {
        width: 100%;
        font-size: 8px;
        font-family: Arial, sans-serif;
        padding: 5px 15px;
        border-top: 1px solid #eee;
        display: flex;
        justify-content: space-between;
        }
        .company-info { 
        line-height: 1.2;
        text-align: left;
        flex: 2;
        }
        .page-info {
        text-align: right;
        flex: 1;
        }
        </style>
        <div class="footer">
        <div class="company-info">
        ' . __('SECURITE SERVICES PLUS • Road Gabes Km 3.5 3000 SFAX TUNISIA') . '<br>
        ' . __('TAXSSPLUS') . ' <br>
        ' . __('PhoneSSPLUS') . ' <br>
        contact@ssplus.tn • www.ssplus.tn
          </div>
        <div class="page-info">
        ' . __('Generated by WAVE PLUS') . '<br>
         ' . now()->format('d/m/Y H:i') . '<br>
         ' . __('Page') . ' <span class="pageNumber"></span> ' . __('Of') . ' <span class="totalPages"></span>
        </div>
        </div>';
    }
}
